<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
	<?php echo $this->paginaTitulo($this->subtitle);?>
	<?php if ($this->usuarioLogueado): ?>
		<div class="menu-admin">
			<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar</a>
		</div>
		<br />
	<?php endif; ?>

	<?php if ($this->usuarioLogueado): ?>
    	<table>
			<tr>
				<th>Id</th>
				<th>Titulo</th>
				<th>sitio</th>
				<th>Fecha</th>
				<th colspan="3">Acciones</th>
			</tr>

			<? foreach( $this->noticias as $noticia ) : ?>
				<tr>
					<td><?php echo $this->escape($noticia->id);?></td>
					<td><?php echo $this->escape($noticia->titulo);?></td>
					<td><?php echo $this->escape($noticia->sitio_nombre);?></td>
					<td nowrap="nowrap"><?php echo $this->escape($noticia->fecha);?></td>
					<td nowrap="nowrap">
						<div class="menu-admin">
							<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/ver/id/<?php echo $noticia->id;?>">Ver</a>
							<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/modificar/id/<?php echo $noticia->id;?>">Modificar</a>
							<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/eliminar/id/<?php echo $noticia->id;?>">Eliminar</a>
						</div>
					</td>
				</tr>
			<?php endforeach;?>
	    </table>
		<br />
		<div class="menu-admin">
			<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar</a>
		</div>
		<br><br><br>
		</div> <!-- contenido -->
	<?php else: ?>

    	<?php foreach( $this->noticias as $noticia ):?>
			<div id="noticia">
				<div id="noticia-titulo"><?php echo $this->escape($noticia->titulo);?></div>
				<div id="noticia-fecha"><?php echo $this->escape( $this->dateFormat( $noticia->fecha ) );?></div>
				<div id="noticia-contenido"><?php echo $noticia->contenido;?></div>
				<div id="noticia-masinfo">
					<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/ver/id/<?php echo $noticia->id;?>">Ver más información</a>
				</div>
				<div class="div-reset"></div>
			</div>
		<?php endforeach; ?>

		<div id="noticia-historico">
			<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/historico">Noticias anteriores...</a>
		</div>
		</div><!-- contenido -->

	<?php endif; ?>
<?php echo $this->render('footer.phtml'); ?>