<?php echo $this->render('header.phtml'); ?>

<h1><?php echo $this->escape($this->title); ?></h1>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
	<form action="<?php echo $this->baseUrl ?>/noticias/<?php echo $this->action; ?>" method="post">
		<div>
			<label for="titulo">titulo:</label>
			<input type="text" name="titulo" value="<?php echo $this->escape(trim($this->noticia->titulo));?>"/>
		</div>
		<div>
			<label for="contenido">contenido:</label>
			<input type="text" name="contenido" value="<?php echo $this->escape($this->noticia->contenido);?>"/>
		</div>

		<div id="boton_formulario">
			<input type="hidden" name="id" value="<?php echo $this->noticia->id; ?>" />
			<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
		</div>

	</form>
</div>
<?php echo $this->render('footer.phtml'); ?>