<h2><?php echo $this->escape ( $this->subtitle );?></h2>

<form action="<?php echo $this->baseUrl?>/admin/noticias/<?php echo $this->action;?>" method="post">
	<div>
		<label for="titulo">titulo</label>
		<input 
			type="text" 
			name="titulo" 
			size="90" 
			value="<?php echo $this->escape(trim($this->noticia->titulo));?>" />
	</div>
	<br/>
	<div>
    	contenido breve:
    	<?php echo $this->formFCKeditor('contenido', $this->noticia->contenido, '100%', 300 );?>
    </div>
	<br/>
	<div>
    	contenido extendido:
    	<?php echo $this->formFCKeditor('contenido_ext', $this->noticia->contenido_ext );?></div>
	<br/>
	<div id="boton_formulario">
		<input type="hidden" name="id" value="<?php	echo $this->noticia->id;?>"/> 
		<input type="submit" name="add" value="<?php echo $this->escape ( $this->buttonText );?>"/>
	</div>
</form>
