<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->noticia) :?>

	<form  class="cssform" action="<?php echo $this->baseUrl ?>/admin/noticias/eliminar"	method="post">
		¿Esta seguro que quiere eliminar la noticia
    		'<?php echo "'{$this->escape(trim($this->noticia->titulo))}'"; ?>'?
    	<br><br>
		<div>
			<input type="hidden" name="id" value="<?php echo $this->noticia->id; ?>"/> 
			<input type="submit" name="del" value="Si" /> 
			<input type="submit" name="del" value="No" />
		</div>
	</form>
<?php else: ?>
	<p>No se pudo encontrar la noticia.</p>
<?php endif;?>
