<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php foreach( $this->noticias as $noticia ): ?>
	<div id="noticia">
		<div id="noticia-titulo">
			<?php echo $this->escape($noticia->titulo);?>
		</div>
        
		<?php
        // FIXME!
        $fecha = explode(" ", $noticia->fecha);
        $hora = $fecha[1];
        $f = explode("-", $fecha[0] );
        ?>
        <div id="noticia-fecha">
        	<?php echo $this->escape($f['2'] . "/" . $f['1'] ."/". $f['0']);?>
        </div>
		<div id="noticia-contenido">
			<?php echo $noticia->contenido;?>
		</div>
		<div id="noticia-masinfo">
			<a href="<?php echo $this->baseUrl; ?>/frontend/noticias/ver/id/<?php echo $noticia->id;?>">Ver más información</a></div>
			<div class="div-reset"></div>
		</div>

<?php endforeach; ?>

<div id="noticia-volver">
	<a href="<?php echo $this->baseUrl; ?>/frontend/noticias/">Volver</a>
</div>

