<?php echo $this->render('header.phtml'); ?>

<h1><?php echo $this->escape($this->title);  ?></h1>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">

<?php if ($this->usuarioLogueado): ?>
  <p><a href="<?php echo $this->baseUrl; ?>/noticias/agregar">Agregar noticia</a></p>
<?php endif; ?>

  <?php
  foreach( $this->noticias as $noticia ) : ?>

    <div id="noticia-titulo"><?php echo $this->escape($noticia->titulo);?></div>
    <div id="noticia-fecha"><?php echo $this->escape($noticia->fecha);?></div>
    <div id="noticia-contenido"><?php echo $noticia->contenido;?></div>

    <?php if ($this->usuarioLogueado): ?>
    	<br>
      <div id="noticia-opciones">
      	Acciones:
        <a href="<?php echo $this->baseUrl; ?>/noticias/ver/id/<?php echo $noticia->id;?>">Ver</a> |
        <a href="<?php echo $this->baseUrl; ?>/noticias/modificar/id/<?php echo $noticia->id;?>">Modificar</a> |
        <a href="<?php echo $this->baseUrl; ?>/noticias/eliminar/id/<?php echo $noticia->id;?>">Eliminar</a>
      </div>
    <?php endif; ?>
	<HR>
  <?php endforeach; ?>


<?php if ($this->usuarioLogueado): ?>
  <p><a href="<?php echo $this->baseUrl; ?>/noticias/agregar">Agregar noticia</a></p>
<?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>