<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
    <h2><?php echo $this->escape($this->subtitle); ?></h2>
            <?php if ($this->usuarioLogueado): ?>

            <div class="menu-admin">
              <a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar nueva Noticia</a>                   
            </div>
            <br/><br/>
        <?php endif; ?>

      <?php
      foreach( $this->noticias as $noticia ) : ?>

        <div id="noticia">
             <?php if ($this->usuarioLogueado): ?>
                <br>
                <table>
                	<tr>
                		<td nowrap="nowrap">
                		<div class="menu-admin">                	                      
                      <a href="<?php echo $this->baseUrl; ?>/noticias/noticias/modificar/id/<?php echo $noticia->id;?>">Modificar Noticia</a> 
                      <a href="<?php echo $this->baseUrl; ?>/noticias/noticias/eliminar/id/<?php echo $noticia->id;?>">Eliminar Noticia</a>
                </div>
                		</td>
                	</tr>
                </table>
                
                <br><br>
            <?php endif; ?>
            <div id="noticia-titulo"><?php echo $this->escape($noticia->titulo);?></div>
            
            <div id="noticia-fecha"><?php echo $this->escape( $this->dateFormat( $noticia->fecha ) );?></div>
            <div id="noticia-contenido"><?php echo $noticia->contenido;?></div>
            <div id="noticia-masinfo"><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/ver/id/<?php echo $noticia->id;?>">Ver más información</a></div>

        <div class="div-reset"></div>
        </div>

      <?php endforeach; ?>


    <?php if ($this->usuarioLogueado): ?>

          <div class="menu-admin">
          	<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/agregar">Agregar nueva Noticia</a>
          </div>
            <br><br><br>
    <?php endif; ?>

      <div id="noticia-historico"><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/historico">Noticias anteriores...</a></div>
</div>

<?php echo $this->render('footer.phtml'); ?>