<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
	<?php echo $this->paginaTitulo($this->subtitle);?>

	<?php foreach( $this->noticias as $noticia ) : ?>

        <div id="noticia">
			<div id="noticia-titulo"><?php echo $this->escape($noticia->titulo);?></div>			
			<div id="noticia-fecha"><?php echo $this->escape( $this->dateFormat( $noticia->fecha ) );?></div>
			<div id="noticia-contenido"><?php echo $noticia->contenido;?></div>
			<div id="noticia-masinfo">
				<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/ver/id/<?php echo $noticia->id;?>">Ver más información</a>
			</div>
			<div class="div-reset"></div>
		</div>

    <?php endforeach; ?>

	<div id="noticia-historico">
      	<a href="<?php echo $this->baseUrl; ?>/noticias/noticias/historico">Noticias anteriores...</a></div>
	</div>
</div>
<?php echo $this->render('footer.phtml'); ?>