<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">

  <?php if ($this->usuarioLogueado): ?>
  <table>
    <tr>
      <td><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/modificar/id/<?php echo $this->noticia->id;?>">Modificar</a></td>
      <td><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/eliminar/id/<?php echo $this->noticia->id;?>">Eliminar</a></td>
    </tr>
  </table>
  <?php endif; ?>

 <div id="noticia-titulo"><?php echo $this->escape($this->noticia->titulo);?></div>
    <?php
                // FIXME!
                $fecha = explode(" ", $this->noticia->fecha);
                $hora = $fecha[1];
                $f = explode("-", $fecha[0] );
            ?>
    <div id="noticia-fecha"><?php echo $this->escape($f['2'] . "/" . $f['1'] ."/". $f['0']);?></div>
    <div id="noticia-contenido"><?php echo $this->noticia->contenido;?></div>
    <div id="noticia-contenidoext"><?php echo $this->noticia->contenido_ext;?></div>
    <br>
    <div id="noticia-volver"><a href="<?php echo $this->baseUrl; ?>/noticias/noticias/">Volver</a></div>
</div>

<?php echo $this->render('footer.phtml'); ?>
