<h2><?php echo $this->escape($this->subtitle); ?></h2>

<form action="<?php echo $this->baseUrl ?>/menu/menu/<?php echo $this->action; ?>" method="post">

<div>
    <label for="item">Item:</label>
    <?php if( $this->pagina ) :?>
        <input type="text" name="item" size="45" value="<?php echo $this->escape(trim($this->pagina->titulo));?>"/>
    <?php else :?>
        <input type="text" name="item" size="45" value="<?php echo $this->escape(trim($this->item->item));?>"/>
    <?php endif; ?>
</div>

<div>
    <label for="destino">Destino:</label>

    <?php if( $this->pagina ) :?>
        <input type="text" name="destino" size="80" value="/paginas/paginas/ver/id/<?php echo $this->escape($this->pagina->id);?>"/>
    <?php else :?>
        <input type="text" name="destino" size="80" value="<?php echo $this->escape($this->item->destino);?>"/>
    <?php endif; ?>

</div>

<div>
    <label for="posicion">Posición:</label>
    <input type="text" name="posicion" size="4" value="<?php echo $this->escape($this->item->posicion);?>"/>
</div>

<div>
    <label for="privado">Privado:</label>
    <select name="privado">
    <option value="1" <?php if ($this->escape($this->item->privado) == 1) echo 'selected'; ?>>Si</option>
    <option value="0" <?php if ($this->escape($this->item->privado) == 0) echo 'selected'; ?>>No</option>
    </select>
</div>

<div>
    <label for="estado">Estado:</label>
    <select name="estado">
    <option value="1" <?php if ($this->escape($this->item->estado) == 1) echo 'selected'; ?>>Activo</option>
    <option value="0" <?php if ($this->escape($this->item->estado) == 0) echo 'selected'; ?>>Inactivo</option>
    </select>
</div>
<br>
<div id="boton_formulario">
    <input type="hidden" name="id" value="<?php echo $this->item->id; ?>" />
    <input type="submit" name="add"
    value="<?php echo $this->escape($this->buttonText); ?>" />
</div>

</form>
