<h2><?php echo $this->escape($this->subtitle); ?></h2>
	
<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/menu/agregar">Agregar</a>
</div>
<br>
<table>
	<tr>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/id/asc/<?php echo !$this->orden_asc;?>">id</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/item/asc/<?php echo !$this->orden_asc;?>">Item</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/destino/asc/<?php echo !$this->orden_asc;?>">Destino</a></th>
		<th><a title="Privado" href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/privado/asc/<?php echo !$this->orden_asc;?>">Priv</a></th>
		<th><a title="Estado" href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/estado/asc/<?php echo !$this->orden_asc;?>">Est</a></th>
		<th><a title="Posición" href="<?php echo $this->baseUrl; ?>/admin/menu/index/orden/posicion/asc/<?php echo !$this->orden_asc;?>">Pos</a></th>
	    <th>Acciones</th>
	</tr>
	<?php foreach( $this->menu as $items ):?>
		<tr>
			<td>
				<?php echo $this->escape($items->id);?>
			</td>
			<td nowrap="nowrap">
				<?php echo $this->escape($items->item);?>
			</td>
			<td nowrap="nowrap">
				<a href="<?php echo $this->baseUrl.$this->escape($items->destino);?>">
					<?php echo $this->escape($items->destino);?>
				</A>
			</td>
			<td align="center">
				<img border="0"	src="<?php echo $this->baseUrl ?>/html/images/estado_<?php echo $items->privado;?>.png"/>
			</td>
	
			<td align="center">
				<img border="0"	src="<?php echo $this->baseUrl ?>/html/images/estado_<?php echo $items->estado;?>.png"/>
			</td>
	
			<td>
				<?php echo $this->escape($items->posicion);?>
			</td>
            <td nowrap="nowrap">
				<div class="menu-admin">		
					<a title="Modificar" href="<?php echo $this->baseUrl;?>/admin/menu/modificar/id/<?php echo $items->id;?>">Mod</a>
					<a title="Eliminar" href="<?php echo $this->baseUrl;?>/admin/menu/eliminar/id/<?php echo $items->id;?>">Eli</a>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<br>
<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/menu/agregar">Agregar</a>
</div>
  
