<h2><?php echo $this->escape($this->subtitle); ?></h2>
	
<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/menu/agregar">Agregar ítem</a>
</div>
<br>
<table>
	<tr>
		<th>id</th>
		<th>Item</th>
		<th>Destino</th>
		<th>Privado</th>
		<th>Estado</th>
		<th>Posición</th>
	    <th>Acciones</th>
	</tr>
	<?php foreach( $this->menu as $items ):?>
		<tr>
			<td>
				<?php echo $this->escape($items->id);?>
			</td>
			<td nowrap="nowrap">
				<?php echo $this->escape($items->item);?>
			</td>
			<td nowrap="nowrap">
				<a href="<?php echo $this->baseUrl.$this->escape($items->destino);?>">
					<?php echo $this->escape($items->destino);?>
				</A>
			</td>
			<td align="center">
				<img border="0"	src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $items->privado;?>.png"/>
			</td>
	
			<td align="center">
				<img border="0"	src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $items->estado;?>.png"/>
			</td>
	
			<td>
				<?php echo $this->escape($items->posicion);?>
			</td>
            <td nowrap="nowrap">
				<div class="menu-admin">		
					<a href="<?php echo $this->baseUrl;?>/admin/menu/modificar/id/<?php echo $items->id;?>">Modificar</a>
					<a href="<?php echo $this->baseUrl;?>/admin/menu/eliminar/id/<?php echo $items->id;?>">Eliminar</a>
				</div>
			</td>
		</tr>
	<?php endforeach; ?>
</table>
<br>
<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/menu/agregar">Agregar ítem</a>
</div>
  
