<h2><?php echo $this->escape($this->subtitle);?></h2>

<?php echo $this->render('menupag/_boton_agregar.phtml'); ?>
<br/>
<table>
	<tr>
		<th>id</th>
		<th>fecha</th>
		<th>título</th>
         <th colspan="4">Acciones</th>
    </tr>
    <?php foreach( $this->paginas as $pagina ) : ?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl."/paginas/paginas/ver/id/".$pagina->id;?>">
					<?php echo $this->escape($pagina->id);?>
				</A>
			</td>
			<td nowrap>
				<?php echo $this->escape($this->dateFormat($pagina->fecha));?>
			</td>
			<td>
				<a href="<?php echo $this->baseUrl."/paginas/paginas/ver/id/".$pagina->id;?>">
					<?php echo $this->escape($pagina->titulo);?>
				</A>
			</td>
            <td nowrap="nowrap">
				<div class="menu-admin">
					<a href="<?php echo $this->baseUrl;?>/paginas/paginas/ver/id/<?php echo $pagina->id;?>">Ver</a>
					<a href="<?php echo $this->baseUrl;?>/admin/paginas/modificar/id/<?php echo $pagina->id;?>">Modificar</a>
					<a href="<?php echo $this->baseUrl;?>/admin/paginas/eliminar/id/<?php echo $pagina->id;?>">Eliminar</a>
					<a href="<?php echo $this->baseUrl;?>/admin/menu/agregar/pagina/<?php echo $pagina->id;?>">Agregar al menú</a>
				</div>
			</td>
		</tr>
    <?php endforeach; ?>
</table>
<br/>
<?php echo $this->render('menupag/_boton_agregar.phtml'); ?>