<h2><?php echo $this->escape($this->subtitle); ?></h2>

<form action="<?php echo $this->baseUrl ?>/admin/menu/<?php echo $this->action; ?>" method="post">

	<div>
		<label for="item">Item:</label>
        <input 
        	type="text" 
        	name="item" 
        	size="45"
			value="<?php echo $this->escape(trim($this->item->item));?>"/>
	</div>
	<div>
		<label for="destino">Destino:</label>
        <input 
        	type="text" 
        	name="destino" 
        	size="60"
			value="<?php echo $this->escape($this->item->destino);?>"/>
	</div>
	<div>
		<label for="posicion">Posición:</label>
		<input 
			type="text"
			name="posicion" 
			size="4"
			value="<?php echo $this->escape($this->item->posicion);?>"/>
	</div>
	<div>
		<label for="privado">Privado:</label>
		<input type='radio' name="privado" value="1" <?php if ($this->escape($this->item->privado) == 1) echo 'checked="checked"'; ?>>Si
		<input type='radio' name="privado" value="0" <?php if ($this->escape($this->item->privado) == 0) echo 'checked="checked"'; ?>>No
	</div>

	<div>
		<label for="estado">Estado:</label> 
		<input type='radio' name="estado" value="1" <?php if ($this->escape($this->item->estado) == 1) echo 'checked="checked"'; ?>>Activo
		<input type='radio' name="estado" value="0" <?php if ($this->escape($this->item->estado) == 0) echo 'checked="checked"'; ?>>Inactivo
	</div>
	<br>
	<div id="boton_formulario">
		<input type="hidden" name="id" value="<?php echo $this->item->id;?>"/>
		<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>"/>
	</div>
</form>