<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->item) :?>
	<form class="cssform" action="<?php echo $this->baseUrl ?>/admin/menu/eliminar"	method="post">
		¿Está seguro que quiere eliminar el menú '<?php echo $this->escape($this->item->item); ?>'?
		<br><br>
		<div>
			<input type="hidden" name="id" value="<?php echo $this->item->id; ?>"/> 
			<input type="submit" name="del" value="Si" />
			<input type="submit" name="del" value="No" />
		</div>
	</form>
<?php else: ?>
	<p>Este menú no existe.</p>
<?php endif;?>