<?php echo $this->render('header.phtml');?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
    <h2><?php echo $this->escape($this->subtitle); ?></h2>

    <?php if ($this->usuarioLogueado): ?>
    <table>
        <tr>
            <td><a href="<?php echo $this->baseUrl; ?>/menu/menu/modificar/id/<?php echo $this->item->id;?>">Modificar</a></td>
            <td><a href="<?php echo $this->baseUrl; ?>/menu/menu/eliminar/id/<?php echo $this->item->id;?>">Eliminar</a></td>
        </tr>
    </table>
    <?php endif; ?>

    <div>
        Id:&nbsp;
        <?php echo $this->escape($this->item->id); ?>
    </div>

    <div>
        Item:&nbsp;
        <?php echo $this->escape($this->item->item); ?>
    </div>

    <div>
        Destino:&nbsp;
        <?php echo $this->escape($this->item->destino); ?>
    </div>

    <div>
        Privado:&nbsp;
        <img border="0" src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $this->item->privado; ?>.png" />
    </div>

    <div>
        Estado:&nbsp;
        <img border="0" src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $this->item->estado; ?>.png" />
    </div>

    <div>
        Posición:&nbsp;
        <?php echo $this->escape($this->item->posicion); ?>
    </div>

</div>
<?php echo $this->render('footer.phtml');?>