<h2><?php echo $this->escape($this->subtitle);?></h2>

<form class="cssform" action="<?php echo $this->baseUrl?>/admin/menupag/<?php echo $this->action;?>" method="post">
	
	<input 
		type="hidden" 
		name="id_pagina" 
		size="2"
		value="<?php echo $this->escape(trim($this->menupag->id_pagina));?>"/>
	

	<p>
		<label for="id_menu">id menu:</label>
		<input 
			type="text"
			name="id_menu" 
			size="2"
			value="<?php echo $this->escape(trim($this->menupag->id_menu));?>"/>
	</p>
	<p>
		<label for="titulo">Título:</label>
		<input 
			type="text" 
			name="titulo" 
			size="40"
			value="<?php echo $this->escape(trim($this->menupag->titulo));?>"/>
	</p>
	<p>
		<label for="link">Link:</label>
		<input 
			type="text" 
			name="link"
			size="40" 
			maxlength="100"
			value="<?php echo $this->escape(trim($this->menupag->link));?>"/>
	</p>
	<p>
		<label for="alt">Tooltip:</label>
		<input 
			type="text" 
			name="alt"
			size="40" 
			maxlength="100"
			value="<?php echo $this->escape(trim($this->menupag->alt));?>"/>
	</p>
	<br>
	<div>
		<input type="hidden" name="id_pag" value="<?php	echo $this->id;?>"/>
		<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText);?>"/>
	</div>
</form>