<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->menupag) :?>

  <form class="cssform" action="<?php echo $this->baseUrl ?>/admin/menupag/eliminar" method="post">
	¿Está seguro que quiere eliminar el menu de la pagina 
		'<?php echo $this->escape($this->menupag->titulo); ?>'?
<br><br>

	<div>
		<input 
			type="hidden" 
			name="id"
			value="<?php echo $this->menupag->id_pagina; ?>"/>
		<input 
			type="hidden" 
			name="menu"
			value="<?php echo $this->menupag->id_menu; ?>"/>
		<input type="submit" name="del" value="Si"/>
		<input type="submit" name="del" value="No"/>
	</div>
  </form>

<?php else: ?>
	<p>No se pudo encontrar la página.</p>
<?php endif;?>

