<?php echo $this->render('header.phtml'); ?>

<form action="<?php echo $this->baseUrl ?>/usuarios/<?php echo $this->action; ?>" method="post">
	<div>
		<label for="usuario">Usuario</label>
		<input type="text" name="usuario" value="<?php echo $this->escape(trim($this->usuario->usuario));?>"/>
	</div>
	<div>
		<label for="password">Password</label>
		<input type="password" name="password" value="<?php echo $this->escape($this->usuario->password);?>"/>
	</div>
	<div>
		<label for="nombre">Nombre</label>
		<input type="text" name="nombre" value="<?php echo $this->escape($this->usuario->nombre);?>"/>
	</div>
	<div>
		<label for="apellido">Apellido</label>
		<input type="text" name="apellido" value="<?php echo $this->escape($this->usuario->apellido);?>"/>
	</div>
	<div>
		<label for="mail">Mail</label>
		<input type="text" name="mail" value="<?php echo $this->escape($this->usuario->mail);?>"/>
	</div>
	<div id="formbutton">
		<input type="hidden" name="id" value="<?php echo $this->usuario->id; ?>" />
		<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
	</div>
</form>

<?php echo $this->render('footer.phtml'); ?>