<?php echo $this->render('header.phtml'); ?>

<div id="cabecera">
    <h1><?php echo $this->escape($this->title); ?></h1>
</div>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">


    <?php if(!empty($this->message)) :?>
        <div id="mensaje">
            <?php echo $this->escape($this->message);?>
        </div>
    <?php endif; ?>

    <?php echo $this->render('usuarios/_form.phtml'); ?>

</div>
<?php echo $this->render('footer.phtml'); ?>