<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
    <h2><?php echo $this->escape($this->subtitle); ?></h2>
    <?php if ($this->usuarioLogueado): ?>
    	<div class="menu-admin">
			<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/modificar/id/<?php echo $this->usuario->id;?>">Modificar</a>
            <a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/eliminar/id/<?php echo $this->usuario->id;?>">Eliminar</a>
    	</div><br>
    <?php endif; ?>

<table>
	<tr>
		<th><label for="usuario">Id:&nbsp;</label></th>
		<td><?php echo $this->escape(trim($this->usuario->id));?></td>		
	</tr>
	<tr>
		<th><label for="usuario">Usuario:&nbsp;</label></th>
		<td><?php echo $this->escape(trim($this->usuario->usuario));?></td>	
	</tr>
	<tr>
		<th><label for="password">Password:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->password);?></td>	
	</tr>
	<tr>
		<th><label for="nombre">Nombre:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->nombre);?></td>	
	</tr>
	<tr>
		<th><label for="apellido">Apellido:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->apellido);?></td>	
	</tr>
	<tr>
		<th><label for="mail">Mail:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->mail);?></td>	
	</tr>
	<tr>
		<th><label for="estado">Estado:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->estado);?></td>	
	</tr>
	<tr>
		<th><label for="creado">Creado:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->creado);?></td>	
	</tr>
	<tr>
		<th><label for="modificado">Modif:&nbsp;</label></th>
		<td><?php echo $this->escape($this->usuario->modificado);?></td>	
	</tr>
</table>
</div>

<?php echo $this->render('footer.phtml'); ?>
