<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
    <h2><?php echo $this->escape($this->subtitle); ?></h2>
    <table>
        <tr>
            <th>Selector</th>
            <th>Descripción</th>
            <th colspan="3">Acciones</th>
        </tr>

            <?php
                    foreach( $this->selectores as $selector ):?>
                        <tr>
                        <td><?php echo $this->escape($selector->selector); ?></td>
                        <td><?php echo $this->escape($selector->descripcion);?></td>
                        <td><a href="<?php echo $this->baseUrl ?>/configuraciones/configuraciones/ver/id/<?php echo $this->escape($selector->id_selector)?>">Ver</a></td>
                        <td><a href="<?php echo $this->baseUrl ?>/configuraciones/configuraciones/modificar/id/<?php echo $this->escape($selector->id_selector)?>">Modificar</a></td>
                        <td>Eliminar</td>
                        </tr>
                     <?php endforeach; ?>
    </table>

</div>
<?php echo $this->render('footer.phtml'); ?>
