<h2><?php echo $this->escape($this->subtitle);?></h2>

<?php if ($this->pagina) :?>

	<form class="cssform" action="<?php echo $this->baseUrl ?>/admin/paginas/eliminar" method="post">
		¿Está seguro que quiere eliminar la pagina 
			'<?php echo $this->escape($this->pagina->titulo); ?>'?
		<br><br>

		<div>
			<input type="hidden" name="id" value="<?php echo $this->pagina->id; ?>"/> 
			<input type="submit" name="del" value="Si"/>
			<input type="submit" name="del" value="No"/>
		</div>
	</form>
<?php else: ?>
	<p>No se pudo encontrar la página.</p>
<?php endif;?>