<?php
$url_action = $this->baseUrl.'/admin/paginas/'.$this->action;
$subtitulo = $this->escape(trim($this->subtitle));
?>
<?php echo $this->PaginaTitulo($subtitulo);?>

<form action="<?php echo $url_action ?>" method="post">
	<div>
		<label for="titulo">titulo:</label>
		<input
			type="text"
			name="titulo"
			size="100"
			value="<?php echo $this->pagina->titulo?>"/>
	</div>
	
	<?php echo $this->render('paginas/_botones_submenu.phtml');?>

    <?php echo $this->formFCKeditor('contenido',$this->pagina->contenido);?>

	<?php echo $this->render('paginas/_boton_formulario.phtml');?>

</div>
</form>