<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2><?php echo $this->escape($this->subtitle); ?></h2>

  <?php if ($this->usuarioLogueado): ?>
      <div id="acciones">
    Acciones:
      <a href="<?php echo $this->baseUrl; ?>/paginas/paginas/modificar/id/<?php echo $this->pagina->id;?>">Modificar</a> |
      <a href="<?php echo $this->baseUrl; ?>/paginas/paginas/eliminar/id/<?php echo $this->pagina->id;?>">Eliminar</a>
    </div>
  <?php endif; ?>
    <br />
  <div id="pagina-titulo">
    <?php echo $this->escape(trim($this->pagina->titulo));?>
  </div>
  <div id="pagina-contenido">
    <?php echo $this->pagina->contenido;?>
  </div>

</div>

<?php echo $this->render('footer.phtml'); ?>
