<script src="http://www.google.com/jsapi"></script>

<?php if( $this->scriptJs == 'prototype' ) :?>
	<script> google.load("prototype", "1.6");</script>
<?php endif; ?>

<?php if( $this->scriptJs == 'scriptaculous' ) :?>
	<script>google.load("prototype", "1.6");</script>
	<script>google.load("scriptaculous", "1.8.1");</script>
<?php endif; ?>

<?php if( $this->scriptJs == 'jquery' ) :?>
	<script>google.load("jquery", "1.2.3");</script>
<?php endif; ?>

<?php if( $this->scriptJs == 'mootools' ) :?>
	<script>google.load("mootools", "1.11");</script>
<?php endif; ?>
  
<?php if( $this->scriptJs == 'dojo' ) :?>
	<script>google.load("dojo", "1.1.1");</script>
<?php endif; ?>
  
<script src="<?php echo $this->baseUrl;?>/public/scripts/cms.js" type="text/javascript"></script>
