    <div id="pie">
		Copyright 2007
    </div>
    <br>
    <span style="text-align:right;"><a href="http://framework.zend.com" title="Sitio Oficial de Zend Framework"><img border="0" src="<?php echo $this->baseUrl ?>/public/images/PoweredBy_ZF_4LightBG.png" alt="Powered By Zend Framework"></A></span>
    </div>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-126600-13";
urchinTracker();
</script>

  </body>
</html>
