	    <div id="pie">
			 Copyright <?php echo date('Y'); ?>
	    </div>   
    </div>
  <?php
  $analytics = $this->basePath 
  	. DIRECTORY_SEPARATOR
  	. 'application'
  	. DIRECTORY_SEPARATOR
  	. 'views' 
  	. DIRECTORY_SEPARATOR
  	. 'scripts'
  	. DIRECTORY_SEPARATOR
  	. 'google_analytics.phtml';
  	
  if(file_exists( $analytics ) ){
	echo $this->render("google_analytics.phtml");
  }
  
   ?>
  </body>
</html>
