<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml');?>

<div id="contenido">
	<?php if(!empty($this->message)) :?>
		<div id="mensaje">
			<?php echo $this->escape($this->message);?>
	    </div>
    <?php endif; ?>
	<?php echo $this->layout()->content; ?>
</div>

<?php echo $this->render('footer.phtml');?>

