<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/site.css" />

    <?php if( $this->scriptJs == 'prototype' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/prototype/prototype.js" type="text/javascript"></script>
    <?php endif; ?>

    <?php if( $this->scriptJs == 'scriptaculous' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/prototype/prototype.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/scriptaculous/scriptaculous.js" type="text/javascript"></script>
    <?php endif; ?>

    <?php if( $this->scriptJs == 'jquery' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/jquery/jquery.js" type="text/javascript"></script>
    <?php endif; ?>

    <script src="<?php echo $this->baseUrl;?>/public/scripts/cms.js" type="text/javascript"></script>


  </head>

  <body>
    <div id="contenedor">

    <div id="cabecera">
        <h1><?php echo $this->escape($this->title);  ?></h1>
        <?php if( $this->user ) echo "usuario: ".$this->escape($this->user->usuario);?>
    </div>

