<?php echo $this->render('header.phtml'); ?>

<div id="cabecera">
<h1><?php echo $this->escape($this->title);  ?></h1>
</div>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">

<?php if ($this->usuarioLogueado): ?>
	<p><a href="<?php echo $this->baseUrl; ?>/paginas/agregar">Agregar página</a></p>
<?php endif; ?>

	<table>
	<tr>
		<th>id</th>
		<th>fecha</th>
	 	<th>título</th>


	<?php if ($this->usuarioLogueado): ?>
	 	<th colspan="3">Acciones</th>
	<?php endif; ?>

	</tr>
	<?php
	foreach( $this->paginas as $pagina ) : ?>
			<tr>
				<td><a href="<?php echo $this->baseUrl . "/paginas/ver/id/" . $pagina->id; ?> "><?php echo $this->escape($pagina->id);?></A></td>
				<td><?php echo $this->escape($pagina->fecha);?></td>
				<td><a href="<?php echo $this->baseUrl . "/paginas/ver/id/" . $pagina->id; ?> "><?php echo $this->escape($pagina->titulo);?></A></td>

				<?php if ($this->usuarioLogueado): ?>
					<td><a href="<?php echo $this->baseUrl; ?>/paginas/ver/id/<?php echo $pagina->id;?>">Ver</a></td>
					<td><a href="<?php echo $this->baseUrl; ?>/paginas/modificar/id/<?php echo $pagina->id;?>">Modificar</a></td>
					<td><a href="<?php echo $this->baseUrl; ?>/paginas/eliminar/id/<?php echo $pagina->id;?>">Eliminar</a></td>
				<?php endif; ?>

			</tr>
	<?php endforeach; ?>
	</table>

<?php if ($this->usuarioLogueado): ?>
	<p><a href="<?php echo $this->baseUrl; ?>/paginas/agregar">Agregar página</a></p>
<?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>