<h1>Ayuda para usar el Admin</h1>

<ol>
  <li><a href="#subsitio">Crear un "sub-sitio" o "sección"</a></li>
  <li> Item two </li>
</ol>
<br/>

<a name="subsitio"><h1>Crear un "sub-sitio" o "sección"</h1></a>
<p>En la parte superior del sitio (cabezal) aparece inmediatamente después del logo un 
menú horizontal que puede se usado para crear una serie de "subsitios" (sitios dentro del sitio principal) o 
"secciones" (similar al caso anterior, la diferencia es conceptual más que funcional)</p>
<p>Estas secciones son independientes unas de otras, por lo que se puede tener en cada una
información independiente de la otra, es decir, los menús, las noticias, las faqs, etc (todas 
las funcionalidades que dispone el sistema, pero para cada sub-sitio / sección.</p>
<p>URL: <a href="<?php echo $this->baseUrl; ?>/admin/sitios/">/admin/sitios/</a> > Opción "Agregar"</p>