<form action="<?php echo $this->baseUrl ?>/menu/<?php echo $this->action; ?>" method="post">
<div>
<label for="item">Item</label>
<input type="text" name="item"
value="<?php echo $this->escape(trim($this->item->item));?>"/>
</div>
<div>
<label for="destino">Destino</label>
<input type="text" name="destino"
value="<?php echo $this->escape($this->item->destino);?>"/>
</div>
<div>
<label for="destino">estado</label>
<select name="estado">
<option value="1" <?php if ($this->escape($this->item->estado) == 1) echo 'selected'; ?>>Activo</option>
<option value="0" <?php if ($this->escape($this->item->estado) == 0) echo 'selected'; ?>>Desactivado</option>
</select>
</div>
<div id="formbutton">
<input type="hidden" name="id" value="<?php echo $this->item->id; ?>" />
<input type="submit" name="add"
value="<?php echo $this->escape($this->buttonText); ?>" />
</div>
</form>
