<h2><?php echo $this->escape($this->subtitle); ?></h2>

<form action="<?php echo $this->baseUrl ?>/menus/menus/<?php echo $this->action; ?>" method="post">

<!-- NOMBRE -->
<div>
	<label for="nombre">Nombre:</label>
	<input type="text" name="nombre"
	value="<?php echo $this->escape(trim($this->menu->nombre));?>" />
	<?php if(isset($this->messages['nombre'])){echo '<span class="error-campo-formulario">'.$this->messages['nombre'].'</span>';}?>
</div>

<!-- TITULO -->
<div>
	<label for="titulo">Título:</label>
	<input type="text" name="titulo"
	value="<?php echo $this->escape(trim($this->menu->titulo));?>" />
	<?php if(isset($this->messages['titulo'])){echo '<span class="error-campo-formulario">'.$this->messages['titulo'].'</span>';}?>
</div>


<!-- DESCRIPCION -->
<div>
	<label for="descripcion">Descripción:</label>
	<input type="text" name="descripcion"
	value="<?php echo $this->escape($this->menu->descripcion);?>" />
	<?php if(isset($this->messages['descripcion'])){echo '<span class="error-campo-formulario">'.$this->messages['descripcion'].'</span>';}?>
</div>


<!-- POSICION -->
<div>
	<label for="posicion">Posición:</label>
	<input type="text" name="posicion" size="4"
	value="<?php echo $this->escape($this->menu->posicion);?>" />
	<?php if(isset($this->messages['posicion'])){echo '<span class="error-campo-formulario">'.$this->messages['posicion'].'</span>';}?>
</div>


<!-- PRIVADO -->
<div>
	<label for="privado">Privado:</label>
	<select name="privado">
		<option value="1" <?php if ($this->escape($this->menu->privado) == 1) echo 'selected="selected"'; ?>>Si</option>
		<option value="0" <?php if ($this->escape($this->menu->privado) == 0) echo 'selected="selected"'; ?>>No</option>
	</select>
	<?php if(isset($this->messages['privado'])){echo '<span class="error-campo-formulario">'.$this->messages['privado'].'</span>';}?>
</div>


<!-- ESTADO -->
<div>
	<label for="estado">Estado:</label>
	<select name="estado">
		<option value="1" <?php if ($this->escape($this->menu->estado) == 1) echo 'selected="selected"'; ?>>Activo</option>
		<option value="0" <?php if ($this->escape($this->menu->estado) == 0) echo 'selected="selected"'; ?>>Inactivo</option>
	</select>
	<?php if(isset($this->messages['estado'])){echo '<span class="error-campo-formulario">'.$this->messages['estado'].'</span>';}?>
</div>


<div id="formbutton">
	<input type="hidden" name="id" value="<?php echo $this->menu->id; ?>" />
	<input type="submit" name="add"
	value="<?php echo $this->escape($this->buttonText); ?>" />
</div>

</form>
