<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/site.css" />

<style type="text/css">
	DIV#cabecera H1{
	  margin:0;
	  padding:0;
	  font-size:22px;
	  color:gray;
	}
	DIV#cabecera{	  
	  border:1px solid #cccccc;
	  padding:10px;
	  background-color:<?php
	  if( isset($this->configuracion->sitio_color_cabezal)) {
	  	echo $this->configuracion->sitio_color_cabezal;
	  }
	  ?>;
	}
	DIV#pie{
	  clear:both;
	  border-top:1px solid #CCCCCC;
	  text-align:center;
	  background-color:<?php 
	  if (isset($this->configuracion->sitio_color_pie)) {
	  	echo $this->configuracion->sitio_color_pie;
	  }
	  ?>;
	  padding:5px;
	}
</style> 