
    <?php if( $this->scriptJs == 'prototype' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/prototype/prototype.js" type="text/javascript"></script>
    <?php endif; ?>

    <?php if( $this->scriptJs == 'scriptaculous' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/prototype/prototype.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/scriptaculous/scriptaculous.js" type="text/javascript"></script>
    <?php endif; ?>

    <?php if( $this->scriptJs == 'jquery' ) :?>
        <script src="<?php echo $this->baseUrl;?>/public/scripts/jquery/jquery.js" type="text/javascript"></script>
    <?php endif; ?>

    <script src="<?php echo $this->baseUrl;?>/public/scripts/cms.js" type="text/javascript"></script>
