<div id="menu">
  <ul>
    <li><a href="<?php echo $this->baseUrl;?>">Home</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/noticias/">Noticias</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/usuarios/">Usuarios</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/faqs/">FAQs</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/paginas/">Paginas</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/menu/">Menues</a></li>
	<li><a href="<?php echo $this->baseUrl;?>/configuraciones/">Configuraciones</a></li>
  </ul>
</div>
