<div id="menu">
  <ul>
    <li><a href="<?php echo $this->baseUrl;?>">Home</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/noticias/">Noticias</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/usuarios/">Listado de usuarios</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/faqs/">Listado de FAQs</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/paginas/">Listado de Paginas</a></li>
    <li><a href="<?php echo $this->baseUrl;?>/menu/">Listado de Menues</a></li>
  </ul>
</div>
