CREATE TABLE `menu` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(255) NOT NULL,
  `estado` CHAR(1) BINARY NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;
