<h2><?php echo $this->escape ( $this->subtitle );?></h2>

<form class="cssform" action="<?php echo $this->baseUrl?>/admin/menus/<?php	echo $this->action;?>" method="post">

	<p>
		<label for="nombre">Nombre:</label>
		<input 
			type="text" 
			name="nombre" 
			size="50"
			value="<?php echo $this->escape ( trim ( $this->menu->nombre ) );?>" />
    		<?php
			if (isset($this->messages ['nombre'] )) {
				echo '<span class="error-campo-formulario">' . $this->messages ['nombre'] . '</span>';
			}
			?>
	</p>
	<p>
		<label for="descripcion">Descripción:</label>
		<input 
			type="text"
			name="descripcion" 
			size="50"
			value="<?php echo $this->escape ( $this->menu->descripcion );?>" />
    		<?php
			if (isset ( $this->messages ['descripcion'] )) {
				echo '<span class="error-campo-formulario">' . $this->messages ['descripcion'] . '</span>';
			}
			?>
	</p>
	<p>
		<label for="posicion">Posición:</label> 
		<input 
			type="text"
			name="posicion" 
			size="4"
			value="<?php echo $this->escape ( $this->menu->posicion );?>" />
    		<?php
			if (isset ( $this->messages ['posicion'] )) {
				echo '<span class="error-campo-formulario">' . $this->messages ['posicion'] . '</span>';
			}
			?>
	</p>
	<p>
		<label for="privado">Privado:</label>
		<input type='radio' name="privado" value="1" <?php if ($this->escape($this->menu->privado) == 1) echo 'checked="checked"'; ?>>Si
		<input type='radio' name="privado" value="0" <?php if ($this->escape($this->menu->privado) == 0) echo 'checked="checked"'; ?>>No
   	<?php
		if (isset ( $this->messages ['privado'] )) {
			echo '<span class="error-campo-formulario">' . $this->messages ['privado'] . '</span>';
		}
		?>
	</p>
	<p>
		<label for="estado">Estado:</label> 
		<input type='radio' name="estado" value="1" <?php if ($this->escape($this->menu->estado) == 1) echo 'checked="checked"'; ?>>Activo
		<input type='radio' name="estado" value="0" <?php if ($this->escape($this->menu->estado) == 0) echo 'checked="checked"'; ?>>Inactivo
    	<?php
		if (isset ( $this->messages ['estado'] )) {
			echo '<span class="error-campo-formulario">' . $this->messages ['estado'] . '</span>';
		}
		?>
	</p>
	<div id="boton_formulario">
		<input type="hidden" name="id" value="<?php	echo $this->menu->id;?>" /> 
		<input type="submit" name="add" value="<?php echo $this->escape ( $this->buttonText );?>"/>
	</div>
</form>