<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->menu) :?>
	<form class="cssform" action="<?php echo $this->baseUrl ?>/admin/menus/eliminar" method="post">
		¿Está seguro que quiere eliminar el menú '<?php echo $this->escape($this->menu->nombre); ?>'?
		<br><br>
		<div>
			<input type="hidden" name="id" value="<?php echo $this->menu->id; ?>"/> 
			<input type="submit" name="del" value="Si"/>
			<input type="submit" name="del" value="No"/>
		</div>
	</form>
<?php else: ?>
	<p>Este menú no existe.</p>
<?php endif;?>