<?php echo $this->paginaTitulo( $this->subtitle ); ?>
<?php echo $this->render('sitios/_opcion_agregar.phtml'); ?>

<?php $url_base = $this->baseUrl . '/admin/sitios';?>

<table>
  <tr>
    <th>id</th>
    <th>nombre</th>
    <th>titulo</th>
    <th>descripción</th>
    <th>orden</th>
    <th>creación</th>
    <th>por defecto</th>
    <th colspan="3">Acciones</th>
  </tr>

<?php foreach( $this->sitios as $sitio): ?>
	<tr>
    	<td><?php echo $sitio->id;?></td>
    	<td><?php echo $sitio->nombre;?></td>
    	<td><?php echo $sitio->titulo;?></td>
    	<td><?php echo $sitio->descripcion; ?></td>
    	<td><?php echo $sitio->orden; ?></td>
    	<td><?php echo $this->dateFormat( $sitio->fecha_creacion );?></td>
    	<td>
    		<?php if($sitio->por_defecto): ?>
    			<img border="0"	src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $sitio->por_defecto;?>.png"/>
			<?php else: ?>
				&nbsp;
    		<?php endif; ?>
    	</td>

    	<td>
    		<div class="menu-admin">
    			<?php echo $this->htmlLink($url_base.'/ver/id/'.$sitio->id, "Ver");?>
    			<?php echo $this->htmlLink($url_base.'/modificar/id/'.$sitio->id, "Modificar");?>
    			<?php echo $this->htmlLink($url_base.'/eliminar/id/'.$sitio->id, "Eliminar");?>
			</div>
    	</td>
  	</tr>
<?php endforeach; ?>

</table>
<?php echo $this->render('sitios/_opcion_agregar.phtml'); ?>