	<h2><?php echo $this->paginaTitulo($this->subtitle); ?></h2>
	
    <?php if ($this->usuarioLogueado): ?>
    	<div class="menu-admin">
    		<a href="<?php echo $this->baseUrl; ?>/admin/sitios/modificar/id/<?php echo $this->sitio->id;?>">Modificar</a>
			<a href="<?php echo $this->baseUrl; ?>/admin/sitios/eliminar/id/<?php echo $this->sitio->id;?>">Eliminar</a>
		</div>
		<br>
    <?php endif; ?>


	<table>
		<tr>
			<th>nombre:&nbsp;</th>
			<td><?php echo $this->escape(trim($this->sitio->nombre));?></td>
		</tr>
		<tr>
			<th>titulo:&nbsp;</th>
			<td><?php echo $this->escape(trim($this->sitio->titulo));?></td>
		</tr>
		<tr>
			<th>Descripción:&nbsp;</th>
			<td><?php echo $this->escape(trim($this->sitio->descripcion));?></td>
		</tr>
		<tr>
			<th>Orden:&nbsp;</th>
			<td><?php echo $this->escape(trim($this->sitio->orden));?></td>
		</tr>
		<tr>
			<th>Por defecto:&nbsp;</th>
			<td>
			<?php if($this->sitio->por_defecto): ?>
    			<img border="0"	src="<?php echo $this->baseUrl ?>/public/images/estado_<?php echo $this->sitio->por_defecto;?>.png"/>
			<?php else: ?>
				&nbsp;
    		<?php endif; ?>
			</td>
		</tr>
		<tr>
			<th>Creado:&nbsp;</th>
			<td><?php echo $this->escape($this->sitio->fecha_creacion);?></td>
		</tr>
	</table>