<?php //echo $this->render('header.phtml'); ?>
<?php //echo $this->render('menu.phtml'); ?>

<!-- <div id="contenido">  -->

	<?php echo $this->paginaTitulo($this->subtitle); ?></h2>
	
    <?php if ($this->usuarioLogueado): ?>
    	<div class="menu-admin">
    		<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/modificar/id/<?php echo $this->usuario->id;?>">Modificar</a>
			<a href="<?php echo $this->baseUrl; ?>/usuarios/usuarios/eliminar/id/<?php echo $this->usuario->id;?>">Eliminar</a>
		</div>
		<br>
    <?php endif; ?>

	<table>
		<tr>
			<th><label for="nombre">nombre:&nbsp;</label></th>
			<td><?php echo $this->escape(trim($this->sitio->nombre));?></td>
		</tr>
		<tr>
			<th><label for="descripcion">Descripción:&nbsp;</label></th>
			<td><?php echo $this->escape(trim($this->sitio->descripcion));?></td>
		</tr>
		<tr>
			<th><label for="creado">Creado:&nbsp;</label></th>
			<td><?php echo $this->escape($this->sitio->fecha_creacion);?></td>
		</tr>
	</table>
<!-- </div>  -->

<?php //echo $this->render('footer.phtml'); ?>
