
	<?php echo $this->paginaTitulo("Eliminar Sitio");?>

	<?php if ($this->sitio) :?>
  		<form action="<?php echo $this->baseUrl ?>/admin/sitios/eliminar" method="post">
			<p>
				¿Esta seguro que quiere eliminar el sitio 
				'<?php echo $this->escape($this->sitio->nombre); ?>'?
			</p>
			<div id="boton_formulario">
				<input type="hidden" name="id" value="<?php echo $this->sitio->id; ?>"/> 
				<input type="submit" name="del" value="Si"/>
				<input type="submit" name="del" value="No"/>
			</div>
		</form>
	<?php else: ?>
  		<p>No se pudo encontrar el usuario.</p>
	<?php endif;?>

