<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->usuario) :?>
  <form class="cssform" action="<?php echo $this->baseUrl ?>/admin/usuarios/eliminar" method="post">
    ¿Esta seguro que quiere eliminar el usuario '<?php echo $this->escape($this->usuario->usuario); ?>'?
    <br><br>
    <div>
      <input type="hidden" name="id" value="<?php echo $this->usuario->id; ?>" />
      <input type="submit" name="del" value="Si" />
      <input type="submit" name="del" value="No" />
    </div>
  </form>
<?php else: ?>
  <p>No se pudo encontrar el usuario.</p>
<?php endif;?>