<h2><?php echo $this->escape($this->subtitle); ?></h2>

<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/faqs/agregar">Agregar FAQ</a>
</div>
<div class="div-reset"></div>
<br />

<table>
	<tr>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/faqs/index/orden/id/asc/<?php echo !$this->orden_asc;?>">Id</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/faqs/index/orden/pregunta/asc/<?php echo !$this->orden_asc;?>">Pregunta</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/faqs/index/orden/fecha/asc/<?php echo !$this->orden_asc;?>">Fecha</a></th>
		<th colspan="3">Acciones</th>
	</tr>
	<?php foreach( $this->faqs as $faq ): ?>
		<tr>
			<td><?php echo $this->escape($faq->id);?></td>
			<td nowrap="nowrap"><?php echo $this->escape($faq->pregunta);?></td>
			<td nowrap="nowrap"><?php echo $this->escape($faq->fecha);?></td>
			<td nowrap="nowrap">
				<div class="menu-admin">
					<a href="<?php echo $this->baseUrl; ?>/admin/faqs/ver/id/<?php echo $faq->id;?>">Ver</a>
					<a href="<?php echo $this->baseUrl; ?>/admin/faqs/modificar/id/<?php echo $faq->id;?>">Modificar</a>
					<a href="<?php echo $this->baseUrl; ?>/admin/faqs/eliminar/id/<?php echo $faq->id;?>">Eliminar</a>
				</div>
			</td>
		</tr>
	<?php endforeach;?>
</table>
<br />
<div class="menu-admin">
	<a href="<?php echo $this->baseUrl; ?>/admin/faqs/agregar">Agregar FAQ</a>
</div>
<div class="div-reset"></div>
