<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2><?php echo $this->escape($this->subtitle); ?></h2>

  <?php if ($this->usuarioLogueado): ?>
	  <div class="menu-admin">
		<a href="<?php echo $this->baseUrl; ?>/faqs/faqs/agregar">Agregar FAQ</a>                   
      </div>
      <div class="div-reset"></div>
      <br/>
	<?php endif; ?>

    <?php
    foreach( $this->faqs as $faq ) : ?>
         <?php if ($this->usuarioLogueado): ?>
                <div class="menu-admin">
 					<a href="<?php echo $this->baseUrl; ?>/faqs/faqs/modificar/id/<?php echo $faq->id;?>">Modificar FAQ</a>
                   	<a href="<?php echo $this->baseUrl; ?>/faqs/faqs/eliminar/id/<?php echo $faq->id;?>">Eliminar FAQ</a>
                </div>
                <br><br>

        <?php endif; ?>

       <div id="faq-titulo"><strong>Pregunta:</strong> <?php echo $this->escape($faq->pregunta), " ({$this->escape($this->dateFormat( $faq->fecha )) })" ;?></div><br>
       <div id="faq-respuesta"><strong>Respuesta:</strong> 
       	<?php echo $this->escape($faq->respuesta);?>
       </div>
        <br><br>


    <?php endforeach; ?>

    <?php if ($this->usuarioLogueado): ?>

            <div class="menu-admin">                   
	             <a href="<?php echo $this->baseUrl; ?>/faqs/faqs/agregar">Agregar FAQ</a>
            </div>
            <br/><br/>
        <?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>
