<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->usuarioLogueado): ?>
	<div class="menu-admin">
		<a href="<?php echo $this->baseUrl;?>/admin/faqs/modificar/id/<?php echo $this->faq->id;?>">
			Modificar
		</a>
		<a href="<?php echo $this->baseUrl;?>/admin/faqs/eliminar/id/<?php echo $this->faq->id;?>">
			Eliminar
		</a>
	</div>
	<br>
<?php endif; ?>

<div id="faq-titulo">
	<?php echo $this->escape($this->faq->pregunta)."({$this->escape($this->dateFormat( $this->faq->fecha )) })" ;?>
</div>
<br>
<div id="faq-respuesta">
	<?php echo $this->faq->respuesta;?>
</div>
