<?php echo $this->render('header.phtml'); ?>

<h1><?php echo $this->escape($this->title);  ?></h1>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">

<?php if ($this->usuarioLogueado): ?>
	<p><a href="<?php echo $this->baseUrl; ?>/noticias/agregar">Agregar noticia</a></p>
<?php endif; ?>

	<table>
	<tr>
		<th>fecha</th>
	 	<th>titulo</th>
	 	<th>contenido</th>

	<?php if ($this->usuarioLogueado): ?>
	 	<th colspan="3">Acciones</th>
	<?php endif; ?>

	</tr>
	<?php
	foreach( $this->noticias as $noticia ) : ?>
			<tr>
				<td><?php echo $this->escape($noticia->fecha);?></td>
				<td><a href="<?php echo $this->baseUrl; ?>/noticias/ver/id/<?php echo $noticia->id;?>"><?php echo $noticia->titulo;?></a></td>
				<td><?php echo $noticia->contenido;?></td>

				<?php if ($this->usuarioLogueado): ?>
					<td><a href="<?php echo $this->baseUrl; ?>/noticias/ver/id/<?php echo $noticia->id;?>">Ver</a></td>
					<td><a href="<?php echo $this->baseUrl; ?>/noticias/modificar/id/<?php echo $noticia->id;?>">Modificar</a></td>
					<td><a href="<?php echo $this->baseUrl; ?>/noticias/eliminar/id/<?php echo $noticia->id;?>">Eliminar</a></td>
				<?php endif; ?>

			</tr>
	<?php endforeach; ?>
	</table>

<?php if ($this->usuarioLogueado): ?>
	<p><a href="<?php echo $this->baseUrl; ?>/noticias/agregar">Agregar noticia</a></p>
<?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>