<h2>Listado de archivos</h2>

<?php echo $this->render('archivos/_opcion_agregar.phtml'); ?>
	<table>
	  <tr>
	    <th>
	    	<a href="<?php echo $this->baseUrl; ?>/admin/archivos/index/orden/id/asc/<?php echo !$this->orden_asc;?>">
	    		Id
	    	</a>
	    </th>
		<th>
			<a href="<?php echo $this->baseUrl; ?>/admin/archivos/index/orden/nombre/asc/<?php echo !$this->orden_asc;?>">
				Nombre
			</a>
		</th>	    
		<th>
			<a title="Previsualización" href="<?php echo $this->baseUrl; ?>/admin/archivos/index/orden/nombre/asc/<?php echo !$this->orden_asc;?>">
				Prev
			</a>
		</th>
	    <th>
	    	<a href="<?php echo $this->baseUrl; ?>/admin/archivos/index/orden/descripcion/asc/<?php echo !$this->orden_asc;?>">
	    		Descripción
	    	</a>
	    </th>
	    <th>Acciones</th>
	  </tr>

	  <?php foreach( $this->archivos as $archivo): ?>
		<tr>
	    	<td><?php echo $archivo->id;?></td>
	    	<td>
	    		<a rel="lightbox" href="<?php echo $this->baseUrl.'/userfiles/'.$archivo->nombre;?>"  
	    			title="<?php echo $archivo->nombre;?>" id="<?php echo $archivo->nombre;?>">
	    			<?php echo $archivo->nombre;?>
	    		</a>
	    	</td>	    	
	    	<td>
	    		<a rel="lightbox" href="<?php echo $this->baseUrl.'/userfiles/'.$archivo->nombre;?>"  
	    			title="<?php echo $archivo->nombre;?>" id="<?php echo $archivo->nombre;?>">
	    			<img src="<?php echo $this->baseUrl.'/userfiles/'.$archivo->nombre;?>" height="50" width="50">
	    		</a>
	    	</td>
	    	<td><?php echo $archivo->descripcion; ?></td>
	    	<td nowrap="nowrap">
                	<div class="menu-admin">
    	            	<a title="Modificar" href="<?php echo $this->baseUrl; ?>/admin/archivos/modificar/id/<?php echo $archivo->id;?>">Mod</a>
        	        	<a title="Eliminar" href="<?php echo $this->baseUrl; ?>/admin/archivos/eliminar/id/<?php echo $archivo->id;?>">Eli</a>
        	        </div>
			</td>
	  	</tr>
	<?php endforeach; ?>
	</table>
	<?php echo $this->render('archivos/_opcion_agregar.phtml'); ?>