<h2><?php echo $this->escape ( $this->subtitle ); ?></h2>

<form class="cssform" action="<?php echo $this->baseUrl?>/admin/items/<?php	echo $this->action;?>" method="post">
	<p>
		<label for="item">Item:</label> 
		<input 
			type="text" 
			name="item" 
			size="50" 
			value="<?php echo $this->escape(trim($this->item->item));?>"/>
    	<?php
		if (isset($this->messages['item'])){
			echo '<span class="error-campo-formulario">'.$this->messages['item'].'</span>';
		}
		?>
	</p>
	<p>
		<label for="destino">Destino:</label>
		<input 
			type="text" 
			name="destino" 
			size="50"	
			value="<?php echo $this->escape($this->item->destino);?>" />
    	<?php
		if (isset($this->messages['destino'])){
			echo '<span class="error-campo-formulario">'.$this->messages['destino'].'</span>';
		}
		?>
	</p>
	<p>
		<label for="posicion">Posición:</label>
		<input 
			type="text" 
			name="posicion" 
			size="4" 
			value="<?php echo $this->escape ( $this->item->posicion );?>"/>
    	<?php
		if (isset( $this->messages ['posicion'])){
			echo '<span class="error-campo-formulario">'.$this->messages['posicion'].'</span>';
		}
		?>
	</p>
	<p>
		<label for="privado">Privado:</label>
		<input type='radio' name="privado" value="1" <?php if ($this->escape($this->item->privado) == 1) echo 'checked="checked"'; ?>>Si
		<input type='radio' name="privado" value="0" <?php if ($this->escape($this->item->privado) == 0) echo 'checked="checked"'; ?>>No
		<?php
		if(isset($this->messages['privado'])){
			echo '<span class="error-campo-formulario">'.$this->messages['privado'].'</span>';
		}
		?>
	</p>
	<p>
		<label for="estado">Estado:</label>
		<input type='radio' name="estado" value="1" <?php if ($this->escape($this->item->estado) == 1) echo 'checked="checked"'; ?>>Activo
		<input type='radio' name="estado" value="0" <?php if ($this->escape($this->item->estado) == 0) echo 'checked="checked"'; ?>>Inactivo
	 	<?php
		if (isset($this->messages['estado'])){
			echo '<span class="error-campo-formulario">'.$this->messages['estado'].'</span>';
		}
		?>
	</p>

	<div id="boton_formulario">
		<input type="hidden" name="id" value="<?php echo $this->item->id;?>"/> 
		<input type="hidden" name="idMenu" value="<?php	echo $this->idMenu;?>" /> 
		<input type="submit" name="add"	value="<?php echo $this->escape ( $this->buttonText );?>" />
	</div>
</form>