<h2><?php echo $this->escape($this->subtitle); ?></h2>

<form class="cssform" action="<?php echo $this->baseUrl ?>/admin/archivos/<?php echo $this->action; ?>"
	enctype="multipart/form-data"
	method="post">
	
	<p>
    	<label for="nombre">Previsualización:</label>
    	
    	
    	<a rel="lightbox" href="<?php echo $this->baseUrl.'/userfiles/'.$this->archivo->nombre;?>"  
	    			title="<?php echo $this->archivo->nombre;?>" id="<?php echo $this->archivo->nombre;?>">
	    			<img src="<?php echo $this->baseUrl.'/userfiles/'.$this->archivo->nombre;?>" height="100" width="100">
	    		</a>
	</p>
	

	<?php if($this->action != 'modificar'): ?>
		<p>
	    	<label for="archivo">Archivo:</label>
	        <input type="file" name="archivo" value=""/>
		</p>
	<?php endif; ?>
	<p>
    	<label for="descripcion">Descripción:</label>
        <input type="text" name="descripcion" size="40" value="<?php echo $this->escape(trim($this->archivo->descripcion));?>"/>
	</p>

    <div>
	    <input type="hidden" name="id" value="<?php echo $this->archivo->id; ?>" />
		<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
	</div>
</form>
