<h2>Listado de archivos</h2>
 <form class="cssform" action="<?php echo $this->baseUrl ?>/admin/archivos/<?php echo $this->action; ?>" method="post">
 <p>
 
	<table>
	  <tr>
	    <th>#</th>
	    <th><a href="<?php echo $this->baseUrl; ?>/admin/archivos/asociar/pagina/<?php echo $this->pagina;?>/orden/nombre/asc/<?php echo !$this->orden_asc;?>">Nombre</a></th>
	    <th><a href="<?php echo $this->baseUrl; ?>/admin/archivos/asociar/pagina/<?php echo $this->pagina;?>/orden/nombre/asc/<?php echo !$this->orden_asc;?>">Previsualizar</a></th>
	    <th><a href="<?php echo $this->baseUrl; ?>/admin/archivos/asociar/pagina/<?php echo $this->pagina;?>/orden/descripcion/asc/<?php echo !$this->orden_asc;?>">Descripción</a></th>
	  </tr>

	<?php foreach( $this->archivos as $archivo): ?>
		<tr>
	    	<td>
	    		<input
	    			type="checkbox"
	    			name="asociar<?php echo $archivo['id']; ?>"
	    			value="<?php echo $archivo['id']; ?>"
	    			<?php if($archivo['id_pagina'] == $this->pagina ): ?>
	    				checked="checked"
	    			<?php endif; ?>
	    		>
	    	</td>
	    	
	    	<td>
	    		<a 
	    			rel="lightbox" 
	    			href="<?php echo $this->baseUrl.'/userfiles/'.$archivo['nombre'];?>"
	    			title="<?php echo $archivo['nombre'];?>" 
    				id="<?php echo $archivo['nombre'];?>">
    					<?php echo $archivo['nombre'];?>
	    		</a>
	    	</td>
	    	<td>
	    		<a 
	    			rel="lightbox" 
	    			href="<?php echo $this->baseUrl.'/userfiles/'.$archivo['nombre'];?>"
	    			title="<?php echo $archivo['nombre'];?>" 
    				id="<?php echo $archivo['nombre'];?>">
    					<img src="<?php echo $this->baseUrl.'/userfiles/'.$archivo['nombre'];?>" height="50" width="50">
	    		</a>
	    	</td>

	    	<td><?php echo $archivo['descripcion']; ?></td>
	  	</tr>
	<?php endforeach; ?>
	</table>
	<div>
          <input type="hidden" name="pagina" value="<?php echo $this->pagina; ?>" />
          <input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
    </div>
    </p>
</form>
<br><br><br/>
<?php $url = $this->baseUrl.'/admin/paginas/modificar/id/'.$this->pagina;?>
<a href="<?php echo $url; ?>">Volver a la página</a>