<?php echo $this->render('header.phtml'); ?>

<h1><?php echo $this->escape($this->title); ?></h1>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">

<?php if ($this->pagina) :?>

	<form action="<?php echo $this->baseUrl ?>/paginas/eliminar" method="post">
		<p>¿Esta seguro que quiere eliminar la paginas
		'<?php echo $this->escape($this->pagina->id); ?>'?
		</p>
		<div id="boton_formulario">
			<input type="hidden" name="id" value="<?php echo $this->pagina->id; ?>" />
			<input type="submit" name="del" value="Si" />
			<input type="submit" name="del" value="No" />
		</div>
	</form>

<?php else: ?>
	<p>No se pudo encontrar la pagina.</p>
<?php endif;?>
</div>


<?php echo $this->render('footer.phtml'); ?>