<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->faq):?>
	<form class="cssform" action="<?php echo $this->baseUrl ?>/admin/faqs/eliminar" method="post">
		¿Está seguro que quiere eliminar la FAQ '<?php echo $this->escape($this->faq->pregunta); ?>'?
		<br><br>
		<div>
			<input type="hidden" name="id" value="<?php echo $this->faq->id; ?>" />
			<input type="submit" name="del" value="Si"/> 
			<input type="submit" name="del" value="No"/>
		</div>
	</form>
<?php else: ?>
	<p>No se pudo encontrar la FAQ.</p>
<?php endif;?>
