<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
    <h2><?php echo $this->escape($this->subtitle); ?></h2>

    <?php if ($this->usuarioLogueado): ?>
    <table>
        <tr>
            <td><a href="<?php echo $this->baseUrl; ?>/faqs/faqs/modificar/id/<?php echo $this->faq->id;?>">Modificar</a></td>
            <td><a href="<?php echo $this->baseUrl; ?>/faqs/faqs/eliminar/id/<?php echo $this->faq->id;?>">Eliminar</a></td>
        </tr>
    </table>
    <?php endif; ?>

    <div>
        <label for="id">Id:&nbsp;</label>
        <?php echo $this->escape(trim($this->faq->id));?>
    </div>
    <div>
        <label for="pregunta">pregunta:&nbsp;</label>
        <?php echo $this->escape(trim($this->faq->pregunta));?>
    </div>
    <div>
        <label for="respuesta">respuesta:&nbsp;</label>
        <?php echo $this->escape($this->faq->respuesta);?>
    </div>

</div>

<?php echo $this->render('footer.phtml'); ?>
