<?php echo $this->render('header.phtml'); ?>

<div id="cabecera">
  <h1><?php echo $this->escape($this->title); ?></h1>
</div>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
  <h2><?php echo $this->escape($this->subtitle); ?></h2>

  <form action="<?php echo $this->baseUrl ?>/noticias/noticias/<?php echo $this->action; ?>" method="post">
    <div>
      <label for="titulo">titulo</label>
      <input type="text" name="titulo" size="90" value="<?php echo $this->escape(trim($this->noticia->titulo));?>"/>
    </div>

    <br>

    <div>
      <?php print $this->formFCKeditor( ' contenido' , $this->noticia->contenido); ?>
    </div>

    <br>

    <div id="boton_formulario">
      <input type="hidden" name="id" value="<?php echo $this->noticia->id; ?>" />
      <input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
    </div>

  </form>
</div>
<?php echo $this->render('footer.phtml'); ?>