<?php echo $this->render('header.phtml'); ?>
<!-- TinyMCE -->
<script language="javascript" type="text/javascript" src="<?php echo $this->baseUrl ?>/public/scripts/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script language="javascript" type="text/javascript">
	tinyMCE.init({
		mode : "textareas",
		theme : "advanced",
		plugins : "table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,zoom,media,searchreplace,print,contextmenu,paste,directionality,fullscreen",
		theme_advanced_buttons1_add_before : "save,newdocument,separator",
		theme_advanced_buttons1_add : "fontselect,fontsizeselect",
		theme_advanced_buttons2_add : "separator,insertdate,inserttime,preview,zoom,separator,forecolor,backcolor",
		theme_advanced_buttons2_add_before: "cut,copy,paste,pastetext,pasteword,separator,search,replace,separator",
		theme_advanced_buttons3_add_before : "tablecontrols,separator",
		theme_advanced_buttons3_add : "emotions,iespell,media,advhr,separator,print,separator,ltr,rtl,separator,fullscreen",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		content_css : "example_word.css",
	    plugi2n_insertdate_dateFormat : "%Y-%m-%d",
	    plugi2n_insertdate_timeFormat : "%H:%M:%S",
		external_link_list_url : "example_link_list.js",
		external_image_list_url : "example_image_list.js",
		media_external_list_url : "example_media_list.js",
		file_browser_callback : "fileBrowserCallBack",
		paste_use_dialog : false,
		theme_advanced_resizing : true,
		theme_advanced_resize_horizontal : false,
		theme_advanced_link_targets : "_something=My somthing;_something2=My somthing2;_something3=My somthing3;",
		paste_auto_cleanup_on_paste : true,
		paste_convert_headers_to_strong : false,
		paste_strip_class_attributes : "all",
		paste_remove_spans : false,
		paste_remove_styles : false
	});

	function fileBrowserCallBack(field_name, url, type, win) {
		// This is where you insert your custom filebrowser logic
		alert("Filebrowser callback: field_name: " + field_name + ", url: " + url + ", type: " + type);

		// Insert new URL, this would normaly be done in a popup
		win.document.forms[0].elements[field_name].value = "someurl.htm";
	}
</script>
<!-- /TinyMCE -->

<div id="cabecera">
<h1><?php echo $this->escape($this->title); ?></h1>
</div>

<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
	<h2><?php echo $this->escape($this->subtitle); ?></h2>
	<form action="<?php echo $this->baseUrl ?>/noticias/noticias/<?php echo $this->action; ?>" method="post">
		<div>
			<label for="titulo">titulo:</label>
			<input type="text" name="titulo" size="100" value="<?php echo $this->escape(trim($this->noticia->titulo));?>"/>
		</div>
	<!--
		<div>
			<label for="contenido">contenido:</label>
			<input type="text" name="contenido" value="<?php echo $this->escape($this->noticia->contenido);?>"/>
		</div>
	-->
		<br>
		<div>
			<textarea id="contenido" name="contenido" rows="15" cols="80" style="width: 100%">
				<?php echo $this->noticia->contenido;?>
			</textarea>
		</div>
		<br>

		<div id="boton_formulario">
			<input type="hidden" name="id" value="<?php echo $this->noticia->id; ?>" />
			<input type="submit" name="add" value="<?php echo $this->escape($this->buttonText); ?>" />
		</div>

	</form>
</div>
<?php echo $this->render('footer.phtml'); ?>