<div id="noticia-titulo">
	<?php echo $this->escape($this->noticia->titulo);?>
</div>

 <?php if ($this->usuarioLogueado): ?>
    	<div class="menu-admin">
    		<a href="<?php echo $this->baseUrl; ?>/admin/noticias/modificar/id/<?php echo $this->noticia->id;?>">Modificar</a>
			<a href="<?php echo $this->baseUrl; ?>/admin/noticias/eliminar/id/<?php echo $this->noticia->id;?>">Eliminar</a>
		</div>
		<br>
<?php endif; ?>
    
<?php
// FIXME!
$fecha = explode(" ", $this->noticia->fecha);
$hora = $fecha[1];
$f = explode("-", $fecha[0] );
?>
<div id="noticia-fecha">
	<?php echo $this->escape($f['2'] . "/" . $f['1'] ."/". $f['0']);?>
</div>
<div id="noticia-contenido">
	<?php echo $this->noticia->contenido;?>
</div>
<div id="noticia-contenidoext">
	<?php echo $this->noticia->contenido_ext;?>
</div>
<br>