<?php if( count($this->paginasMenues) > 0): ?>
	<div id="menu-pagina">	
		<?php foreach($this->paginasMenues as $paginaMenu):?>
			<?php
			$url_sub_menu = array(
				'url'  => $paginaMenu->link,
				'text' => $paginaMenu->titulo,
				'alt'  => $paginaMenu->alt	
			);					
			$sub_menu[] = $this->htmlLinkArray( $url_sub_menu );
			?>				
		<?php endforeach; ?>				
		<strong>Menú:</strong>&nbsp;<?php echo implode('|', $sub_menu ); ?>
	</div>
<?php endif; ?>