<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php echo $this->render('paginas/_boton_agregar.phtml'); ?>
<br/>

<table>
	<tr>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/paginas/index/orden/id/asc/<?php echo !$this->orden_asc;?>">id</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/paginas/index/orden/fecha/asc/<?php echo !$this->orden_asc;?>">fecha</a></th>
		<th><a href="<?php echo $this->baseUrl; ?>/admin/paginas/index/orden/titulo/asc/<?php echo !$this->orden_asc;?>">título</a></th>
		<th colspan="4">Acciones</th>
    </tr>

    <?php foreach( $this->paginas as $pagina ):?>
		<tr>
			<td>
				<a href="<?php echo $this->baseUrl."/frontend/paginas/ver/id/".$pagina->id;?>">
					<?php echo $this->escape($pagina->id);?>
				</A>
			</td>
			<td nowrap>
				<?php echo $this->escape( $this->dateFormat( $pagina->fecha ));?>
			</td>
			<td>
				<a href="<?php echo $this->baseUrl."/frontend/paginas/ver/id/".$pagina->id;?>">
					<?php echo $this->escape($pagina->titulo);?>
				</A>
			</td>
            <td nowrap="nowrap">
				<div class="menu-admin">
					<a title="Modificar" href="<?php echo $this->baseUrl;?>/admin/paginas/modificar/id/<?php echo $pagina->id;?>">Mod</a>
					<a title="Eliminar" href="<?php echo $this->baseUrl;?>/admin/paginas/eliminar/id/<?php echo $pagina->id;?>">Eli</a>
					<a href="<?php echo $this->baseUrl;?>/admin/menu/agregar/pagina/<?php echo $pagina->id;?>">Agregar al menú</a>
				</div>
			</td>
		</tr>
    <?php endforeach; ?>
</table>
<br/>
<?php echo $this->render('paginas/_boton_agregar.phtml'); ?>