<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<?php
$url_action = $this->baseUrl . '/paginas/paginas/' . $this->action;
$titulo = $this->escape( trim( $this->subtitle ) );
?>

<div id="contenido">
	<?php echo $this->PaginaTitulo( $titulo );?>
	
	<form action="<?php echo $url_action ?>" method="post">
		<div>
			<label for="titulo">titulo:</label> 
			<input type="text" name="titulo" size="100" value="<?php echo $titulo ?>" />
		</div>		
		<br>
		<?php echo $this->render('paginas/_submenu_modificar.phtml'); ?>	
      	<?php print $this->formFCKeditor( ' contenido' , $this->pagina->contenido); ?>
		<?php echo $this->render('paginas/_boton_formulario.phtml'); ?>
	</form>
</div>
<br>

</div> <!-- externo -->

<?php  echo $this->render('footer.phtml'); ?>