<?php echo $this->paginaTitulo($this->subtitle);?>

<?php if ($this->usuarioLogueado): ?>
    	<div class="menu-admin">
    		<a href="<?php echo $this->baseUrl; ?>/admin/paginas/modificar/id/<?php echo $this->pagina->id;?>">Modificar</a>
			<a href="<?php echo $this->baseUrl; ?>/admin/paginas/eliminar/id/<?php echo $this->pagina->id;?>">Eliminar</a>
		</div>
		<br>
<?php endif; ?>

<?php if( $this->pagina ): ?>
	<?php echo $this->render('paginas/_submenu.phtml'); ?>

	<div id="pagina-titulo">
		<?php echo $this->escape(trim($this->pagina->titulo)); ?>
	</div>

	<div id="pagina-contenido">
    	<?php echo $this->pagina->contenido;?>
  	</div>

  	<div id="pagina-archivos">
    	<?php if( count($this->archivos) > 0 ):?>
    		<strong>Archivos</strong>
    		<ul>
    		<?php foreach($this->archivos as $archivo): ?>
    			<li>
    				<a href="<?php echo $this->baseUrl; ?>/userfiles/<?php echo $archivo->nombre;?>">
    					<?php echo $archivo->nombre;?>
    				</a>&nbsp;-&nbsp;<?php echo $archivo->descripcion;?>
    			</li>
    		<?php endforeach; ?>
    		</ul>
    	<?php endif; ?>
  	</div>
<?php else: ?>
  	Página no existente
<?php endif; ?>
