<div id="login-form">
	
	    <form id="form-login" action="<?php echo $this->baseUrl ?>/frontend/autenticacion/login" method="post">
	
			<div>
	    		Su dirección IP actual es: <strong><?php echo $_SERVER['REMOTE_ADDR']; ?></strong>
	    	</div>
	    	<br/>
	    	
	        <div>
	            <label for="usuario">Usuario: </label>
	            <input type="text" id="usuario" name="usuario" value=""/>
	        </div>
	
	        <div>
	            <label for="password">Clave: </label>
	            <input type="password" id="password" name="password" value=""/>
	        </div>
			<br/>
	        <div id="formbutton">
	            <input type="submit" name="login" value="Iniciar Sesión" onclick="login_validar();" />
	        </div>
	        
	    </form>
	    
	</div>