<?php echo $this->render('header.phtml'); ?>
<?php echo $this->render('menu.phtml'); ?>

<div id="contenido">
<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->usuarioLogueado): ?>
    <p><a href="<?php echo $this->baseUrl; ?>/paginas/paginas/agregar">Agregar página</a></p>
<?php endif; ?>

    <table>
    <tr>
        <th>id</th>
        <th>fecha</th>
         <th>título</th>


    <?php if ($this->usuarioLogueado): ?>
         <th colspan="4">Acciones</th>
    <?php endif; ?>

    </tr>
    <?php
    foreach( $this->paginas as $pagina ) : ?>
            <tr>
                <td><a href="<?php echo $this->baseUrl . "/paginas/paginas/ver/id/" . $pagina->id; ?> "><?php echo $this->escape($pagina->id);?></A></td>
                <td nowrap><?php echo $this->escape($pagina->fecha);?></td>
                <td><a href="<?php echo $this->baseUrl . "/paginas/paginas/ver/id/" . $pagina->id; ?> "><?php echo $this->escape($pagina->titulo);?></A></td>

                <?php if ($this->usuarioLogueado): ?>
                    <td><a href="<?php echo $this->baseUrl; ?>/paginas/paginas/ver/id/<?php echo $pagina->id;?>">Ver</a></td>
                    <td><a href="<?php echo $this->baseUrl; ?>/paginas/paginas/modificar/id/<?php echo $pagina->id;?>">Modificar</a></td>
                    <td><a href="<?php echo $this->baseUrl; ?>/paginas/paginas/eliminar/id/<?php echo $pagina->id;?>">Eliminar</a></td>
                    <td><a href="<?php echo $this->baseUrl; ?>/menu/menu/agregar/pagina/<?php echo $pagina->id;?>">Agregar al menú</a></td>
                <?php endif; ?>

            </tr>
    <?php endforeach; ?>
    </table>

<?php if ($this->usuarioLogueado): ?>
    <p><a href="<?php echo $this->baseUrl; ?>/paginas/paginas/agregar">Agregar página</a></p>
<?php endif; ?>

</div>

<?php echo $this->render('footer.phtml'); ?>
