<h2><?php echo $this->escape($this->subtitle); ?></h2>

<?php if ($this->menu) :?>
	<form action="<?php echo $this->baseUrl ?>/admin/menus/eliminar" method="post">
		<p>¿Está seguro que quiere eliminar el menú '<?php echo $this->escape($this->menu->nombre); ?>'?</p>
		<div id="boton_formulario">
			<input type="hidden" name="id" value="<?php echo $this->menu->id; ?>"/> 
			<input type="submit" name="del" value="Si"/>
			<input type="submit" name="del" value="No"/>
		</div>
	</form>
<?php else: ?>
	<p>Este menú no existe.</p>
<?php endif;?>